config/routes.rb
Rails.application.routes.draw do

  mount Shrine::DownloadEndpoint => "/attachments"

  resources :requests do
    resources :photos, except: :index
  end

  resources :users

  get    '/auth/:provider'          => 'omniauth#auth', as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'


  get 'home/index'
  get 'home/landing'
  get 'home/home'
  get '/photos' => 'photos#index'

  root 'home#landing'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
require "image_processing/mini_magick"

class ImageUploader < Shrine
  # Plugins and uploading logic goes here

  include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions   # enable Shrine to handle a hash of files
  plugin :delete_raw # delete processed files after uploading

  process(:store) do |io, context|
    original = io.download

    size_800 = resize_to_fill!(original, 800, 800) { |cmd| cmd.auto_orient } # orient rotated images
    size_500 = resize_to_fill(size_800,  500, 500)
    size_300 = resize_to_fill(size_500,  300, 300)
    size_thumbnail = resize_to_fill(size_300, 64, 64)

    { original: io, large: size_800, medium: size_500, small: size_300, thumbnail: size_thumbnail }
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :request
  include ImageUploader::Attachment.new(:image)


end

app/models/request.rb
class Request < ApplicationRecord

  has_many :photos
  belongs_to :requestor, class_name: 'User', foreign_key: :requestor_id
  belongs_to :photographer, class_name: 'User'

  validates :name, presence: true
  validates :occassion, presence: true
  validates :contact, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests, foreign_key: :requestor_id
  has_many :photos, through: :requests

#  geocoded_by :ip_address
#  after_validation :geocode
  #
  # have to add validations and conditions for when certain columns are validated
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid'],
                      email: authentication_data.info.email
                     ).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user=(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in filter to ensure the user is logged in
  def authenticate!
    unless logged_in?
      redirect_to root_path, notice: "Please log in first"
    end
  end
end

app/controllers/home_controller.rb
  class HomeController < ApplicationController
    before_action :authenticate!, except: [:landing]
    def index
    end

    def theme
    end

    def home
      @request = Request.new(name: current_user.name, contact: current_user.email)
    end
  end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate!

  def show
    @photo = current_user.photos.find(params[:id])
  end

  def index
    @photos = current_user.photos
  end

  def new
    @request = Request.find(params[:request_id])
    @photo = @request.photos.new

    if @request.photographer != current_user
      redirect_to home_home_url, notice: "You aren't the photographer for this event"
    end
  end

  def create
    @request = Request.find(params[:request_id])

    if @request.photographer != current_user
      redirect_to home_home_url, notice: "You aren't the photographer for this event"
    end

    @request.photos.create(photo_params)
    redirect_to request_path(@request)
  end

  def destroy
    @request = Request.find(params[:request_id])
    @photo = current_user.photos.find(params[:id])
    @photo.destroy

    redirect_to home_index_path, notice: "Photo was successfully deleted."
  end

  private


  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/requests_controller.rb
 class RequestsController < ApplicationController
  before_action :authenticate!

  def index
    @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])
    @photo = @request.photos.new

    if @request.photographer != current_user
      redirect_to home_home_url, notice: "You aren't the photographer for this event"
    end
  end

  def new
    @request = Request.new
  end

  def create
    @request = current_user.requests.create!(request_params)
    if @request.valid?
      flash[:success] = "Your request has been sent!"

      PhotographerMailer.new_request(@request).deliver
      RequestorMailer.new_request(@request).deliver

      redirect_to home_home_url
    else

      render :new, status: :unprocessable_entity

    end
  end

  def edit
  end

  def update
  end

  def destroy

  end

  private

  def request_params
    params.require(:request).permit(:name, :contact, :location, :address, :occassion, :pro_camera, :needed_for_entire_event, :special_instructions, :photographer_id)

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to home_home_path
    else
      redirect_to root_path, notice: "There was an error while trying to auhtenticate you"
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
 # TODO, create failure.html.erb
  end
end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to auth_path(provider: 'facebook')
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    # TODO, create failure.html.erb
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
    @user.update_attributes(user_params)
    if @user.valid?
      redirect_to home_home_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :pro_camera, :opt_in)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/home.html.erb
<section class="cta">
  <div class="cta-content">
    <div class="container">
    <%= link_to 'Request Photographer', new_request_path, { class: 'btn btn-default btn-xl', 'data-toggle' => "modal", 'data-target' => '#request-photographer' } %>
    </div>
  </div>
  <div class="overlay"></div>
</section>

<section class="features" id="features">
  <div class="container">
    <div class="section-heading text-center">
      <h2> Capture what matters most, anytime. Anywhere.</h2>
      <p class="text-muted">Never miss a moment again <i class="fa fa-heart"></i></h2></p>
      <hr>
    </div>
    <div class="row">
      <div class="col-lg-4">
      </div>
      <div class="col-lg-8">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-6">
              <div class="feature-item">
                <i class="icon-screen-smartphone text-primary"></i>
                <h3>First, Request a Photographer </h3>
                <p class="text-muted">Whenever you need a momemnt captured, click on the icon in your app "Request a Photographer" to find someone close by to come and take your photo</p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="feature-item">
                <i class="icon-present text-primary"></i>
                <h3>What's the Occasion?</h3>
                <p class="text-muted">Need a photographer for a friend's baby shower next week? Popping the question tonight? Maybe just out with some friends and you'd rather be in front of the camera instead of behind it. Whatever the occcasion, let your photographer know! You can choose a time, location, and specify how long you need your photographer for. </p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="feature-item">
                <i class="icon-camera text-primary"></i>
                <h3> Request Accepted! </h3>
                <p class="text-muted">Awesome! We have found your personal photographer! They have been notified with all of your requests and details. </p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="feature-item">
                <i class="icon-lock-open text-primary"></i>
                <h3>Lock it in</h3>
                <p class="text-muted"> Finally, just check your email with your photographer's information to confirm and you're all set! Once your photos are taken, you will be able to see them all saved right in your app!</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="modal fade" id="request-photographer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Let's get started</h4>
      </div>
      <div class="modal-body">
        <%= form_for @request, html: { class: "new_request form-horizontal" } do |request| %>
          <div class="form-group">
            <%= request.label :photographer_id, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= request.collection_select :photographer_id, User.where.not(id: current_user.id).where(opt_in:true), :id, :name, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= request.label :name, 'Name', class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= request.text_field :name, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= request.label :contact, 'Contact', class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= request.text_field :contact, class: "form-control", placeholder: "yourname@email.com" %>
            </div>
          </div>


          <div class="form-group">
            <%= request.label :address, 'Location', class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= request.text_field :address, class: "form-control" %>
            </div>
          </div>


          <div class="form-group">
            <%= request.label :occasion, 'Occasion', class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= request.text_field :occassion, class: "form-control", placeholder: "Out with friends, Family gathering, etc." %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 inline">
              <%= request.label :pro_camera, class: "checkbox-inline" do %>
                <%= request.check_box :pro_camera %>
                Professional Camera
              <% end %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 inline">
              <%= request.label :needed_for_entire_event, class: "checkbox-inline" do %>
                <%= request.check_box :needed_for_entire_event %>
                Needed for entire event
              <% end %>
            </div>
          </div>

          <div class="form-group">
            <%= request.label :special_instructions, 'Special Instructions', class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= request.text_area :special_instructions, class: "form-control", placeholder: "i.e; Tonight I'm proposing to My girlfriend I don't want her to know that there is someone taking pictures. Please be sure to capture as many candid photos as possible through the entire proposal. We will be right in front of the eiffel tower" %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= request.submit class:'btn btn-warning'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="update-profile" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Profile</h4>
      </div>
      <div class="modal-body">
        <%= form_for current_user, html: { class: "new_request form-horizontal" } do |user| %>


          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 inline">
              <%= user.label :pro_camera, class: "checkbox-inline" do %>
                <%= user.check_box :pro_camera %>
                Professional Camera
              <% end %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 inline">
              <%= user.label :opt_in, class: "checkbox-inline" do %>
                <%= user.check_box :opt_in %>
              Available
              <% end %>
            </div>
          </div>


          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= user.submit "Save", class:'btn btn-warning'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<header class="masthead">
  <div class="container">
    <div class="page-header">
      <h1>
        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
        My Photos
      </h1>
    </div>

    <div class="picturesindex row">

      <% 1.times do %>
      <% current_user.photos.each do |photo| %>
      <% if photo.image_url(:medium) %>
    <div class="col-xs-3 col-md-3 my-photo">
        <%= image_tag(photo.image_url(:medium), class: "img-thumbnail") %>
        <%= link_to request_photo_path(current_user, photo), method: :delete, data: { confirm: 'Delete this photo?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
    </div>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</header>

<div class="modal fade" id="update-profile" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Profile</h4>
      </div>
      <div class="modal-body">
        <%= form_for current_user, html: { class: "new_request form-horizontal" } do |user| %>


          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 inline">
              <%= user.label :pro_camera, class: "checkbox-inline" do %>
                <%= user.check_box :pro_camera %>
                Professional Camera
              <% end %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10 inline">
              <%= user.label :opt_in, class: "checkbox-inline" do %>
                <%= user.check_box :opt_in %>
              Available
              <% end %>
            </div>
          </div>


          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= user.submit "Save", class:'btn btn-warning'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/landing.html.erb
    <header class="masthead">
        <div class="container">
            <div class="row">
                <div class="col-sm-7">
                    <div class="header-content">
                        <div class="header-content-inner">
                            <h1>Find anyone, anywhere, at anytime to pop up and take your photos so that you'll never miss a moment or be left out of the picture again. </h1>
                            <%= link_to 'Login with facebook', auth_path(provider: 'facebook'), class: "btn btn-outline btn-xl" %>
                            <%= link_to 'Login with Instagram', auth_path(provider: 'instagram'), class: "btn btn-outline btn-xl" %>
                        </div>
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="device-container">
                        <div class="device-mockup iphone6_plus portrait gold">
                            <div class="device">
                                <div class="screen">
                                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                    <%= image_tag("Friends-and-Family-1.jpg", class: "landing-page-phone-image") %>
                                </div>
                                <div class="button">
                                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>



</body>
</html>

app/views/home/secondpage.html.erb
<!-- Navigation -->
<nav class="navbar navbar-fixed-top navbar-toggleable-md navbar-light" id="mainNav">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        Menu <i class="fa fa-bars"></i>
    </button>
    <div class="container">
        <a class="navbar-brand" href="#page-top">PhotoPop!</a>
        <div class="collapse navbar-collapse" id="navbarExample">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#contact">My Photos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">Log Out</a>
                </li>
            </ul>
        </div>
    </div>
</nav>




<section class="cta">
    <div class="cta-content">
        <div class="container">
            <!-- <h2>Stop waiting.<br>Start building.</h2> -->

            <a href="#contact" class="btn btn-outline btn-xl">Request Photographer</a>
        </div>
    </div>
    <div class="overlay"></div>
</section>
<section class="features" id="features">
    <div class="container">
        <div class="section-heading text-center">
            <h2> Capture what matters most, anytime. Anywhere.</h2>
            <p class="text-muted">Never miss a moment again <i class="fa fa-heart"></i></h2></p>
            <hr>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <!-- <div class="device-container">
                    <div class="device-mockup iphone6_plus portrait white">
                        <div class="device">
                            <div class="screen">
                                Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else!
                                <img src="img/demo-screen-1.jpg" class="img-fluid" alt=""> </div>
                            <div class="button">
                                You can hook the "home button" to some JavaScript events or just remove it
                            </div>
                        </div>
                    </div>
                </div> -->
            </div>
            <div class="col-lg-8">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-screen-smartphone text-primary"></i>
                                <h3>First, Request a Photographer </h3>
                                <p class="text-muted">Whenever you need a momemnt captured, click on the icon in your app "Request a Photographer" to find someone close by to come and take your photo</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-present text-primary"></i>
                                <h3>What's the Occasion?</h3>
                                <p class="text-muted">Is it a friends baby shower next week? Popping the question tonight? Maybe just out with some friends and you'd rather be in front of the camera instead of behind it. Whatever the occcasion, let your photographer know! You can choose a time, location, and specify how long you need your photographer for. </p>
                            </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-camera text-primary"></i>
                                <h3> Request Accepted! </h3>
                                <p class="text-muted">Awesome! We have found your personal photographer! They have been notified with all of your requests and details. </p>
                            </div>
                        </div>
                      </div>
                      <div class="row">
                         <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-lock-open text-primary"></i>
                                <h3>Lock it in</h3>
                                <p class="text-muted"> Finally, just confirm with your photographer that you are ready to go, and you're all set! Once your photos are taken, you will be able to see them all saved right in your app!</p>
                            </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</section>




<footer>
    <div class="container">
        <p>&copy; 2017 PhotoPop! All Rights Reserved.</p>

    </div>
</footer>

app/views/home/theme.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-fixed-top navbar-toggleable-md navbar-light" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#page-top">PhotoPop!</a>
        </div>
    </nav>

    <header class="masthead">
        <div class="container">
            <div class="row">
                <div class="col-sm-7">
                    <div class="header-content">
                        <div class="header-content-inner">
                            <h1>Request anyone, anywhere, at aytime to pop up and take your photos so that you'll never miss a moment or be left out of the picture again. </h1>

                            <a href="#download"class="btn btn-outline btn-xl">Sign in with <span class="fa fa-instagram"></span>Instagram</a>
                            <%= link_to 'Login with facebook', auth_path(provider: 'facebook') %>


                            <a href="#download"class="btn btn-outline btn-xl">Sign in with <span class="fa fa-instagram"></span>Instagram</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="device-container">
                        <div class="device-mockup iphone6_plus portrait gold">
                            <div class="device">
                                <div class="screen">
                                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                    <%= image_tag("Friends-and-Family-1.jpg", class: "landing-page-phone-image") %>
                                </div>
                                <div class="button">
                                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <footer>
        <div class="container">
            <p>&copy; 2017 PhotoPop! All Rights Reserved.</p>
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a href="#">Privacy</a>
                </li>
                <li class="list-inline-item">
                    <a href="#">Terms</a>
                </li>
                <li class="list-inline-item">
                    <a href="#">FAQ</a>
                </li>
            </ul>
        </div>
    </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="controller-<%= controller_name%> action-<%= action_name%>">
  <!-- <% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= msg %>
    <% end %>
  <% end %> -->
  <nav class="navbar navbar-fixed-top navbar-default" id="mainNav">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#right-hand-nav" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          PhotoPop!
          <% if current_user %>
           <%= current_user.name %>
          <% else %>

          <% end %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="right-hand-nav">
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
            <%= link_to 'Photos','/home/index' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Home','/home/home' %>
          </li>

          <li class="nav-item">
          <% if logged_in? %>
            <%= link_to 'Profile', edit_user_path(current_user), { 'data-toggle' => "modal", 'data-target' => '#update-profile' } %>
          <% end %>
          </li>

          <li class="nav-item">
            <%= link_to 'Logout', logout_path %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <% flash.each  do |key, value| %>
    <div class="alert photographer-success alert-<%= key %>"><%= value %></div>
  <% end %>

  <%= yield %>

  <footer class="navbar-fixed-bottom">
    <div class="container">
      <p>&copy; 2017 PhotoPop! All Rights Reserved.</p>
    </div>
  </footer>


</body>
</html>

app/views/photos/_show.html.erb
<div class="modal fade" id="picture-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <%= image_tag(photo.image_url(:medium), class: "my-photo img-thumbnail") %>

    </div>
  </div>
</div>